attempt to close WS connections only if protocol exists (during delete of a charger)
reason: exceptions as below. if no protocol was set, there was no connection anyway.

java.lang.NullPointerException: Cannot invoke "String.length()" because "v" is null
	at de.rwth.idsg.steve.ocpp.OcppProtocol.fromCompositeValue(OcppProtocol.java:58)
	at de.rwth.idsg.steve.service.ChargePointService.deleteChargePoint(ChargePointService.java:133)
	at de.rwth.idsg.steve.web.controller.ChargePointsController.delete(ChargePointsController.java:188)