remove mariadb 11.x and 12.x from build matrix
reason: github actions fail to start them with error:

"mariadbd: io_uring_queue_init() failed with EPERM: sysctl kernel.io_uring_disabled has the value 2,
or 1 and the user of the process is not a member of sysctl kernel.io_uring_group. (see man 2 io_uring_setup)."

the internet wisdom says to disable io_uring for mariadb, because github ubuntu runners disable it at kernel level.
i could not find a way to pass "skip-innodb-use-native-aio" to mariadb using github actions.